### PR TITLE
Fix dirty signature once memory moved in realloc.

### PR DESCRIPTION
**Pull request by SparkleLin**

### CODE REVIEW

**Comment by yanqi27** [comment]
This fix is not complete. We need to fill the whole freed space since we are not reuse it.

```
            if(iNewSize<lOldSize && gPatchMgr->FloodFreeSpace())
            {
                ::memset((char*)ipUserSpace, USER_FREE_BYTE, lOldSize-iNewSize);
            }
            SCRATCH_SIGNATURE(lpHeader);
```

should be

```
            if(gPatchMgr->FloodFreeSpace())
            {
                ::memset((char*)ipUserSpace, USER_FREE_BYTE, lOldSize);
            }
            SCRATCH_SIGNATURE(lpHeader);
```

Originally, I may want to reuse the old block if it is large enough. However, it needs a new backtrace and smaller request is far less likely than a larger request. Therefore, I decided to discard old block always.
thanks, Lin.

**Comment by yanqi27** [comment]
@SparkleLin 
If you are interested, you are welcome to join the project.

**Comment by SparkleLin** [comment]
Thanks Michael, It's my pleasure to join this great project.

Yes, that's a great idea to use a new block always, and we may need save user space memory temporarily.

Lin

**Comment by SparkleLin** [comment]
@yanqi27 

Thanks Michael, It my pleasure to join this great project.

Yes, it is better to think block moved at all times. According to your changes, we may need back up the user space memory value temporarily. I'm not sure whether it is a good choice to consumer more space during reallocate functionality especially in critical memory situation.

Thanks,
Lin

**Comment by yanqi27** [comment]
@SparkleLin 
I added you to the project. You can merge your fix. Have fun.

**Pull request merged**
